[".local/share/zinit/zinit.git"]
  type = "git-repo"
  url = "https://github.com/zdharma-continuum/zinit.git"
  refreshPeriod = "24h"
  [".local/share/zinit/zinit.git".pull]
    args = ["--rebase", "--autostash"]

[".config/emacs"]
  type = "git-repo"
  url = "https://github.com/doomemacs/doomemacs"
  [".config/emacs".clone]
    args = ["--depth", "1"]

["ThePathOfMastery"]
  type = "git-repo"
  url = "{{ onepasswordRead "op://Personal/ThePathOfMastery Vault/password" }}"
