[".zprezto"]
  type = "git-repo"
  url = "https://github.com/dluksza/prezto.git"
  refreshPeriod = "24h"
  [".zprezto".pull]
    args = ["--recurse-submodules", "--rebase", "--autostash"]
  [".zprezto".clone]
    args = ["--recursive"]

