[".local/share/zinit/zinit.git"]
  type = "git-repo"
  url = "https://github.com/zdharma-continuum/zinit.git"
  refreshPeriod = "24h"
  [".local/share/zinit/zinit.git".pull]
    args = ["--rebase", "--autostash"]
