---
- name: Enable Rosetta2 for Flutter
  shell: softwareupdate --install-rosetta --agree-to-license
  become: true

- name: Install FVM
  community.general.homebrew:
    name: fvm

- name: FVM install stable version
  shell:
    cmd: fvm install stable --setup

- name: FVM install beta version
  shell:
    cmd: fvm install beta --setup

- name: FVM set beta as global
  shell:
    cmd: fvm global beta

- name: FVM Precache Frameworks
  shell:
    cmd: fvm spawn {{ item }} precache --android --ios --macos --web
  loop:
    - stable
    - beta

- name: FVM Install Melos
  shell:
    cmd: fvm spawn {{ item }} pub global activate melos
  loop:
    - stable
    - beta

- name: FVM Install OnePub
  shell:
    cmd: fvm spawn stable pub global activate onepub

- name: Install Android SDKs
  community.general.homebrew_cask:
    name:
      - android-sdk
      - android-ndk
      - android-platform-tools
