---
- stat:
    path: ~/.sdkman
  register: sdkman_check

- name: Install SDKMan
  shell: curl -s "https://get.sdkman.io" | bash
  when: not sdkman_check.stat.exists

- name: Setup SDKMan
  shell: source ~/.sdkman/bin/sdkman-init.sh
  when: not sdkman_check.stat.exists

- shell:
    cmd: source ~/.sdkman/bin/sdkman-init.sh && sdk list java | grep installed | grep --quiet 21.0.4-tem
  failed_when: false
  register: has_java21

- name: SDKMan Java 21.0.4-tem
  shell:
    cmd: source ~/.sdkman/bin/sdkman-init.sh && sdk install java 21.0.4-tem
  when: has_java21.rc != 0

- shell:
    cmd: source ~/.sdkman/bin/sdkman-init.sh && sdk list java | grep installed | grep --quiet 17.0.12.fx-zulu
  failed_when: false
  register: has_java17

- name: SDKMan Java 17.0.12-tem
  shell:
    cmd: source ~/.sdkman/bin/sdkman-init.sh && sdk install java 17.0.12-tem
  when: has_java17.rc != 0
