"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[cmd_duration]
style = "bold bg:#1A237E"
min_time = 500
format = "[ took:$duration]($style)"
